services:
  shell:
    entrypoint:
      - /bin/sh
    image: 368099029718.dkr.ecr.us-west-2.amazonaws.com/aws-scripts
    init: true
    volumes:
      - ./:/home/python/aws-scripts
    working_dir: /home/python/aws-scripts
